- platform: mqtt
  name: "sensTerrazzaTemp"
  unique_id: sensTerrazzaTemp
  icon: mdi:temperature-celsius
  state_topic: "tele/c6d7c2f6063e/SENSOR"
  unit_of_measurement: °C
  value_template: "{{ value_json.temp | float }}"
  json_attributes_topic: "tele/c6d7c2f6063e/SENSOR"
  json_attributes_template: "{{ value_json | tojson }}"
- platform: mqtt
  name: "sensTerrazzaPresses"
  unique_id: sensTerrazzaPresses
  icon: mdi:counter
  state_topic: "tele/c6d7c2f6063e/SENSOR"
  unit_of_measurement: nr°
  value_template: "{{ value_json.presses | float }}"
  json_attributes_topic: "tele/c6d7c2f6063e/SENSOR"
  json_attributes_template: "{{ value_json | tojson }}"
- platform: mqtt
  name: "sensTerrazzaBatt"
  unique_id: sensTerrazzaBatt
  icon: mdi:battery
  state_topic: "tele/c6d7c2f6063e/SENSOR"
  unit_of_measurement: '%'
  value_template: "{{ value_json.batt | float }}"
  json_attributes_topic: "tele/c6d7c2f6063e/SENSOR"
  json_attributes_template: "{{ value_json | tojson }}"
- platform: mqtt
  name: "sensTerrazzaPir"
  unique_id: sensTerrazzaPir
  icon: mdi:brightness-4
  state_topic: "tele/c6d7c2f6063e/SENSOR"
  unit_of_measurement: 'Pir'
  value_template: "{{ value_json.pir | float }}"
  json_attributes_topic: "tele/c6d7c2f6063e/SENSOR"
  json_attributes_template: "{{ value_json | tojson }}"
- platform: mqtt
  name: "sensTerrazzaMag"
  unique_id: sensTerrazzaMag
  icon: mdi:magnet
  state_topic: "tele/c6d7c2f6063e/SENSOR"
  unit_of_measurement: 'Mag'
  value_template: "{{ value_json.mag | float }}"
  json_attributes_topic: "tele/c6d7c2f6063e/SENSOR"
  json_attributes_template: "{{ value_json | tojson }}"
  
