- platform: mqtt
  name: "sensThomasTemp"
  unique_id: sensThomasTemp
  icon: mdi:temperature-celsius
  state_topic: "tele/c76a7927fc73/SENSOR"
  unit_of_measurement: °C
  value_template: "{{ value_json.temp | float }}"
  json_attributes_topic: "tele/c76a7927fc73/SENSOR"
  json_attributes_template: "{{ value_json | tojson }}"
- platform: mqtt
  name: "sensThomasPresses"
  unique_id: sensThomasPresses
  icon: mdi:counter
  state_topic: "tele/c76a7927fc73/SENSOR"
  unit_of_measurement: nr°
  value_template: "{{ value_json.presses | float }}"
  json_attributes_topic: "tele/c76a7927fc73/SENSOR"
  json_attributes_template: "{{ value_json | tojson }}"
- platform: mqtt
  name: "sensThomasBatt"
  unique_id: sensThomasBatt
  icon: mdi:battery
  state_topic: "tele/c76a7927fc73/SENSOR"
  unit_of_measurement: '%'
  value_template: "{{ value_json.batt | float }}"
  json_attributes_topic: "tele/c76a7927fc73/SENSOR"
  json_attributes_template: "{{ value_json | tojson }}"
- platform: mqtt
  name: "sensThomasPir"
  unique_id: sensThomasPir
  icon: mdi:brightness-4
  state_topic: "tele/c76a7927fc73/SENSOR"
  unit_of_measurement: 'Pir'
  value_template: "{{ value_json.pir | float }}"
  json_attributes_topic: "tele/c76a7927fc73/SENSOR"
  json_attributes_template: "{{ value_json | tojson }}"
- platform: mqtt
  name: "sensThomasMag"
  unique_id: sensThomasMag
  icon: mdi:magnet
  state_topic: "tele/c76a7927fc73/SENSOR"
  unit_of_measurement: 'Mag'
  value_template: "{{ value_json.mag | float }}"
  json_attributes_topic: "tele/c76a7927fc73/SENSOR"
  json_attributes_template: "{{ value_json | tojson }}"
- platform: mqtt
  name: "sensThomasToggle"
  unique_id: sensThomasToggle
  icon: mdi:gesture-tap-hold
  state_topic: "tele/c76a7927fc73/SENSOR"
  unit_of_measurement: 'On/Off'
  value_template: "{{ value_json.toggle }}"
  json_attributes_topic: "tele/c76a7927fc73/SENSOR"
  json_attributes_template: "{{ value_json | tojson }}"
